---
all:
  children:
    ubuntu_desktops:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
      vars:
        target_profile: desktop
        install_gui_apps: true

    ubuntu_servers:
      hosts:
        server01:
          ansible_host: 192.168.1.10
      vars:
        target_profile: server
        install_gui_apps: false

    windows:
      hosts:
        winpc01:
          ansible_host: 192.168.1.20
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
        ansible_user: ansible
        ansible_password: "{{ vault_windows_password }}"
