---
- name: Add Google Chrome signing key
  ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    keyring: /etc/apt/keyrings/google-chrome.gpg
  when: ansible_os_family == "Debian"

- name: Add Google Chrome repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/google-chrome.gpg arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome
    state: present
  when: ansible_os_family == "Debian"

- name: Install Google Chrome
  ansible.builtin.apt:
    name: "{{ chrome_package }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"
