---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Install common packages on Ubuntu
  ansible.builtin.apt:
    name: "{{ common_ubuntu_packages }}"
    state: present
  when: ansible_os_family == "Debian"
